---
- name: Copy Graylog configuration file
  template:
    src: "{{ graylog_host_config_file_path }}"
    dest: "{{ graylog_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  when: graylog_config_check.stat.exists
  notify: Restart Graylog