---
- name: Set fact variable for list each items
  set_fact:
    graylog_elasticsearch_facts: "http://{{ item }}:{{ graylog_elasticsearch_port }}"
  with_items: "{{ graylog_elasticsearch_hosts }}"
  register: graylog_elasticsearch_facts_output

- name: Set fact variable for all host Elasticsearch
  set_fact:
    graylog_elasticsearch_host_list: "{{ graylog_elasticsearch_facts_output.results | map(attribute='ansible_facts.graylog_elasticsearch_facts') | list }}"
  when: graylog_elasticsearch_facts_output.results is defined

- name: Copy Graylog configuration file
  template:
    src: "{{ graylog_host_config_file_path }}"
    dest: "{{ graylog_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  when: graylog_config_check.stat.exists
  changed_when: yes
  notify: Restart Graylog

- name: Pre-Check Graylog configuration file in template file
  stat:
    path: "{{ graylog_config_template_path }}"
  register: graylog_config_template_output
  run_once: yes
  delegate_to: 127.0.0.1

- name: Validate Graylog configuration file exists
  assert:
    that: graylog_config_template_output.stat.exists == true
    msg: "No server.conf.j2 in template directory"

- name: Copy Graylog configuration file in case of host doesn't have config file
  template:
    src: server.conf.j2
    dest: "{{ graylog_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  when: not graylog_config_check.stat.exists
  notify: Restart Graylog
