---
- name: Set fact variable for list each items
  set_fact:
    graylog_elasticsearch_facts: "http://{{ item }}:{{ graylog_elasticsearch_port }}"
  with_items: "{{ graylog_elasticsearch_hosts }}"
  register: output_graylog_elasticsearch_facts

- name: Set fact variable for all host Elasticsearch
  set_fact:
    graylog_elasticsearch_host: "{{ output_graylog_elasticsearch_facts.results | map(attribute='ansible_facts.graylog_elasticsearch_facts') | list }}"
  when: output_graylog_elasticsearch_facts.results is defined

- name: Copy Graylog configuration file
  template:
    src: "{{ graylog_host_config_file_path }}"
    dest: "{{ graylog_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  when: graylog_config_check.stat.exists
  changed_when: yes
  notify: Restart Graylog

- name: Copy Graylog configuration file in case of host doesn't have config file
  template:
    src: server.conf.j2
    dest: "{{ graylog_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  when: not graylog_config_check.stat.exists
  notify: Restart Graylog
